import { useRef, useState } from 'react';
import { Archive, Check, Download, FileImage, FileUp, Files, Image, LoaderCircle, MoveDown, MoveUp, RefreshCw, Scissors, Trash2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { PDFDocument } from 'pdf-lib';
import JSZip from 'jszip';
import { importFiles } from '../../modules/scanner.js';
import { downloadBlob, formatBytes } from '../../lib/utils.js';

const TOOLS={imagepdf:{title:'Images to PDF',icon:Image,accept:'image/*',multiple:true},pdfimages:{title:'PDF to Images',icon:FileImage,accept:'.pdf,application/pdf'},compress:{title:'Compress Image',icon:Archive,accept:'image/*'},merge:{title:'Merge PDFs',icon:Files,accept:'.pdf,application/pdf',multiple:true},split:{title:'Split PDF',icon:Scissors,accept:'.pdf,application/pdf'},convert:{title:'Format Converter',icon:RefreshCw,accept:'image/*',multiple:true}};
const read=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
const loadImage=async file=>{const im=new Image();im.src=await read(file);await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=reject});return im};

export default function ToolRunnerV2({id}){
  const tool=TOOLS[id],Icon=tool.icon,input=useRef(null),[files,setFiles]=useState([]),[quality,setQuality]=useState(72),[format,setFormat]=useState('image/jpeg'),[pageSize,setPageSize]=useState('a4'),[orientation,setOrientation]=useState('portrait'),[margin,setMargin]=useState(10),[maxSize,setMaxSize]=useState(2400),[pages,setPages]=useState([]),[selected,setSelected]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function choose(incoming){const selectedFiles=[...incoming];setFiles(id==='imagepdf'||id==='merge'||id==='convert'?prev=>[...prev,...selectedFiles]:selectedFiles);setMessage('');if(id==='pdfimages'&&selectedFiles[0])try{const result=await importFiles(selectedFiles);setPages(result.map((p,i)=>({i,src:p.src})));setSelected(Object.fromEntries(result.map((_,i)=>[i,true])))}catch(e){setMessage(e.message)}if(id==='split'&&selectedFiles[0])try{const pdf=await PDFDocument.load(await selectedFiles[0].arrayBuffer()),count=pdf.getPageCount();setPages(Array.from({length:count},(_,i)=>({i})));setSelected(Object.fromEntries(Array.from({length:count},(_,i)=>[i,true])))}catch(e){setMessage(e.message)}}
  const reorder=(index,delta)=>setFiles(current=>{const next=[...current],target=Math.max(0,Math.min(next.length-1,index+delta));next.splice(target,0,next.splice(index,1)[0]);return next});
  async function run(){if(!files.length)return setMessage('Choose a file first.');setBusy(true);setMessage('');try{
    if(id==='imagepdf'){const doc=new jsPDF({orientation,unit:'mm',format:pageSize});for(let i=0;i<files.length;i++){const im=await loadImage(files[i]),data=await read(files[i]),w=doc.internal.pageSize.getWidth()-margin*2,h=doc.internal.pageSize.getHeight()-margin*2,scale=Math.min(w/im.width,h/im.height);if(i)doc.addPage(pageSize,orientation);doc.addImage(data,files[i].type.includes('png')?'PNG':'JPEG',margin+(w-im.width*scale)/2,margin+(h-im.height*scale)/2,im.width*scale,im.height*scale)}doc.save('images-to-pdf.pdf')}
    if(id==='merge'){const out=await PDFDocument.create();for(const f of files){const pdf=await PDFDocument.load(await f.arrayBuffer()),copied=await out.copyPages(pdf,pdf.getPageIndices());copied.forEach(p=>out.addPage(p))}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'merged.pdf')}
    if(id==='compress'){const im=await loadImage(files[0]),scale=Math.min(1,maxSize/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',quality/100));downloadBlob(blob,'compressed.jpg');setMessage(`Original ${formatBytes(files[0].size)} → compressed ${formatBytes(blob.size)}`)}
    if(id==='convert'){for(const f of files){const im=await loadImage(f);if(format==='application/pdf'){const doc=new jsPDF({orientation:im.width>im.height?'landscape':'portrait',unit:'px',format:[im.width,im.height]});doc.addImage(im,im.width>im.height?'JPEG':'JPEG',0,0,im.width,im.height);doc.save(`${f.name.replace(/\.[^.]+$/,'')}.pdf`)}else{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0);const blob=await new Promise(resolve=>c.toBlob(resolve,format,.92)),ext=format==='image/png'?'png':format==='image/webp'?'webp':'jpg';downloadBlob(blob,`${f.name.replace(/\.[^.]+$/,'')}.${ext}`)}}}
    if(id==='split'){const pdf=await PDFDocument.load(await files[0].arrayBuffer()),out=await PDFDocument.create(),indices=Object.keys(selected).filter(i=>selected[i]).map(Number),copied=await out.copyPages(pdf,indices);copied.forEach(p=>out.addPage(p));downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'split-pages.pdf')}
    if(id==='pdfimages'){const zip=new JSZip();for(const p of pages.filter(x=>selected[x.i]))zip.file(`page-${String(p.i+1).padStart(3,'0')}.jpg`,p.src.split(',')[1],{base64:true});downloadBlob(await zip.generateAsync({type:'blob'}),'pdf-pages.zip')}
    setMessage('Done — your download has started.');
  }catch(e){setMessage(`Could not complete: ${e.message}`)}finally{setBusy(false)}}
  return <div className="tool-runner"><div className="tool-runner-head"><span className="tool-icon"><Icon size={20}/></span><div><h2>{tool.title}</h2><p>Runs locally in your browser. Files are not uploaded.</p></div></div><input ref={input} type="file" accept={tool.accept} multiple={tool.multiple} hidden onChange={e=>choose(e.target.files)}/><button className="upload-zone" onClick={()=>input.current.click()} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('drag-over')}} onDragLeave={e=>e.currentTarget.classList.remove('drag-over')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('drag-over');choose(e.dataTransfer.files)}}><FileUp/><b>Choose {tool.multiple?'files':'a file'} or drop here</b><small>{tool.accept.replaceAll(',',' · ')}</small></button>
  {files.length>0&&<div className="tool-file-list">{files.map((f,i)=><div className="tool-file" key={`${f.name}-${i}`}><span className="file-thumb">{f.type.includes('pdf')?'PDF':<img src={URL.createObjectURL(f)} alt=""/>}</span><span className="file-label"><b>{f.name}</b><small>{formatBytes(f.size)}</small></span>{['imagepdf','merge'].includes(id)&&<><button onClick={()=>reorder(i,-1)} aria-label="Move up"><MoveUp size={15}/></button><button onClick={()=>reorder(i,1)} aria-label="Move down"><MoveDown size={15}/></button></>}<button onClick={()=>setFiles(prev=>prev.filter((_,j)=>i!==j))} aria-label="Remove"><Trash2 size={15}/></button></div>)}</div>}
  {id==='imagepdf'&&files.length>0&&<div className="tool-options"><label>Page size<select value={pageSize} onChange={e=>setPageSize(e.target.value)}><option value="a4">A4</option><option value="letter">Letter</option><option value="legal">Legal</option></select></label><label>Orientation<select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label>Margin<select value={margin} onChange={e=>setMargin(Number(e.target.value))}><option value="0">None</option><option value="10">10 mm</option><option value="18">18 mm</option></select></label></div>}
  {id==='compress'&&files.length>0&&<div className="tool-options"><label>Image quality · {quality}%<input type="range" min="10" max="100" value={quality} onChange={e=>setQuality(+e.target.value)}/></label><label>Maximum dimension<select value={maxSize} onChange={e=>setMaxSize(+e.target.value)}><option value="2400">2400 px</option><option value="1600">1600 px</option><option value="1200">1200 px</option></select></label></div>}
  {id==='convert'&&files.length>0&&<div className="tool-options"><label>Convert to<select value={format} onChange={e=>setFormat(e.target.value)}><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option><option value="application/pdf">PDF</option></select></label></div>}
  {['split','pdfimages'].includes(id)&&pages.length>0&&<div className="tool-page-grid">{pages.map((p,i)=><label key={p.i} className="tool-page-choice"><input type="checkbox" checked={!!selected[p.i]} onChange={e=>setSelected(s=>({...s,[p.i]:e.target.checked}))}/>{p.src?<img src={p.src} alt={`Page ${i+1}`}/>:<span className="pdf-page-preview">{i+1}</span>}<small>Page {i+1}</small></label>)}</div>}
  {message&&<div className="tool-message">{message}</div>}{files.length>0&&<button className="btn-primary tool-run-action" disabled={busy} onClick={run}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} {busy?'Working…':({imagepdf:'Create PDF',pdfimages:'Download selected JPGs',compress:'Compress & download',merge:'Merge PDFs',split:'Extract selected pages',convert:'Convert files'})[id]}</button>}</div>
}
