import {useRef,useState} from 'react';import{FileUp,Image,FileImage,Archive,Files,Scissors,RefreshCw,Download,Trash2,MoveUp,MoveDown,LoaderCircle,Check,Plus}from'lucide-react';import{jsPDF}from'jspdf';import{PDFDocument}from'pdf-lib';import JSZip from'jszip';import{importFiles}from'../../modules/scanner.js';import{downloadBlob,formatBytes}from'../../lib/utils.js';
const SPECS={imagepdf:{name:'Images to PDF',icon:Image,accept:'image/*',multiple:true},pdfimages:{name:'PDF to Images',icon:FileImage,accept:'.pdf,application/pdf'},compress:{name:'Compress Image',icon:Archive,accept:'image/*'},merge:{name:'Merge PDFs',icon:Files,accept:'.pdf,application/pdf',multiple:true},split:{name:'Split PDF',icon:Scissors,accept:'.pdf,application/pdf'},convert:{name:'Format Converter',icon:RefreshCw,accept:'image/*',multiple:true}};
function toData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}function image(file){return new Promise(async(resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=await toData(file)})}
export default function ToolRunner({id}){const spec=SPECS[id],input=useRef(null),[files,setFiles]=useState([]),[quality,setQuality]=useState(72),[format,setFormat]=useState('image/jpeg'),[pages,setPages]=useState([]),[selected,setSelected]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const add=async list=>{const chosen=[...list];if(id==='imagepdf'||id==='merge'||id==='convert')setFiles(p=>[...p,...chosen]);else setFiles(chosen);setMessage('');if(id==='pdfimages'&&chosen[0])try{const rendered=await importFiles(chosen);setPages(rendered.map((p,i)=>({src:p.src,name:p.name,i})));setSelected(Object.fromEntries(rendered.map((_,i)=>[i,true])))}catch(e){setMessage(e.message)}if(id==='split'&&chosen[0])try{const doc=await PDFDocument.load(await chosen[0].arrayBuffer());setPages(Array.from({length:doc.getPageCount()},(_,i)=>({i,name:`Page ${i+1}`})));setSelected(Object.fromEntries(Array.from({length:doc.getPageCount()},(_,i)=>[i,true])))}catch(e){setMessage(e.message)}};const run=async()=>{if(!files.length){setMessage('Choose a file first.');return}setBusy(true);setMessage('');try{if(id==='imagepdf'){const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});for(let i=0;i<files.length;i++){const img=await image(files[i]),data=await toData(files[i]),w=190,h=277,s=Math.min(w/img.width,h/img.height);if(i)doc.addPage();doc.addImage(data,files[i].type.includes('png')?'PNG':'JPEG',(210-img.width*s)/2,(297-img.height*s)/2,img.width*s,img.height*s)}doc.save('images-to-pdf.pdf')}
else if(id==='merge'){const out=await PDFDocument.create();for(const f of files){const pdf=await PDFDocument.load(await f.arrayBuffer()),copied=await out.copyPages(pdf,pdf.getPageIndices());copied.forEach(p=>out.addPage(p))}downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'merged.pdf')}
else if(id==='compress'){const im=await image(files[0]),c=document.createElement('canvas'),scale=Math.min(1,Number($('#compressWidth')?.value||2400)/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',quality/100));downloadBlob(blob,'compressed.jpg');setMessage(`Original ${formatBytes(files[0].size)} · compressed ${formatBytes(blob.size)}`)}
else if(id==='convert'){for(const f of files){const im=await image(f),c=document.createElement('canvas');c.width=im.width;c.height=im.height;c.getContext('2d').drawImage(im,0,0);const blob=await new Promise(r=>c.toBlob(r,format,.92));downloadBlob(blob,`${f.name.replace(/\.[^.]+$/,'')}.${format==='image/png'?'png':format==='image/webp'?'webp':'jpg'}`)}}
else if(id==='split'){const pdf=await PDFDocument.load(await files[0].arrayBuffer()),out=await PDFDocument.create(),indices=Object.keys(selected).filter(k=>selected[k]).map(Number),copied=await out.copyPages(pdf,indices);copied.forEach(p=>out.addPage(p));downloadBlob(new Blob([await out.save()],{type:'application/pdf'}),'split-pages.pdf')}
else if(id==='pdfimages'){const zip=new JSZip();for(const p of pages.filter(x=>selected[x.i]))zip.file(`page-${String(p.i+1).padStart(3,'0')}.jpg`,p.src.split(',')[1],{base64:true});downloadBlob(await zip.generateAsync({type:'blob'}),'pdf-pages.zip')}setMessage('Done — your download has started.')}catch(e){setMessage(`Could not complete: ${e.message}`)}finally{setBusy(false)}};const reorder=(i,d)=>setFiles(a=>{const b=[...a],j=Math.max(0,Math.min(b.length-1,i+d));b.splice(j,0,b.splice(i,1)[0]);return b});const title=spec.name,Icon=spec.icon;
return <div className="tool-runner"><div className="tool-runner-head"><span className="tool-icon"><Icon size={20}/></span><div><h2>{title}</h2><p>Runs locally in your browser. Your files are not uploaded.</p></div></div><input ref={input} type="file" accept={spec.accept} multiple={spec.multiple} hidden onChange={e=>add(e.target.files)}/><button className="upload-zone" onClick={()=>input.current.click()} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('drag-over')}} onDragLeave={e=>e.currentTarget.classList.remove('drag-over')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('drag-over');add(e.dataTransfer.files)}}><FileUp/><b>Choose {spec.multiple?'files':'a file'} or drop here</b><small>{spec.accept.replaceAll(',',' · ')}</small></button>
{files.length>0&&<div className="tool-file-list">{files.map((f,i)=><div className="tool-file" key={`${f.name}-${i}`}><span className="file-thumb">{f.type==='application/pdf'?'PDF':<img src={URL.createObjectURL(f)} alt=""/>}</span><span className="file-label"><b>{f.name}</b><small>{formatBytes(f.size)}</small></span>{(id==='imagepdf'||id==='merge')&&<><button onClick={()=>reorder(i,-1)} aria-label="Move up"><MoveUp size={15}/></button><button onClick={()=>reorder(i,1)} aria-label="Move down"><MoveDown size={15}/></button></>}<button onClick={()=>setFiles(a=>a.filter((_,j)=>j!==i))} aria-label="Remove"><Trash2 size={15}/></button></div>)}</div>}
{id==='compress'&&files.length>0&&<div className="tool-options"><label>Image quality <b>{quality}%</b><input type="range" min="10" max="100" value={quality} onChange={e=>setQuality(+e.target.value)}/></label><label>Max dimension <select id="compressWidth"><option value="2400">Original / 2400px max</option><option value="1600">1600 px</option><option value="1200">1200 px</option></select></label></div>}
{id==='convert'&&files.length>0&&<div className="tool-options"><label>Convert to <select value={format} onChange={e=>setFormat(e.target.value)}><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label></div>}
{(id==='split'||id==='pdfimages')&&pages.length>0&&<div className="tool-page-grid">{pages.map((p,i)=><label key={p.i} className="tool-page-choice"><input type="checkbox" checked={!!selected[p.i]} onChange={e=>setSelected(s=>({...s,[p.i]:e.target.checked}))}/>{p.src?<img src={p.src} alt={p.name}/>:<span className="pdf-page-preview">{i+1}</span>}<small>Page {i+1}</small></label>)}</div>}
{message&&<div className="tool-message">{message}</div>}{files.length>0&&<button className="btn-primary tool-run-action" disabled={busy} onClick={run}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} {busy?'Working…':({imagepdf:'Create PDF',pdfimages:'Download selected JPGs',compress:'Compress & download',merge:'Merge PDFs',split:'Extract selected pages',convert:'Convert images'})[id]}</button>}
</div>}
