import './style.css';
import {importFiles,makePage} from './modules/scanner.js';
import {startCamera,stopCamera,captureFrame} from './modules/camera.js';
import {detectCorners,defaultCorners,perspectiveCrop,boundingCrop} from './modules/crop.js';
import {cssFilter} from './modules/filters.js';
import {downloadPdf,downloadJpgs,buildPdf} from './modules/pdfExport.js';
import {recognizeText} from './modules/ocr.js';
import * as storage from './modules/storage.js';
const $=s=>document.querySelector(s),ui={rail:$('#thumbnailRail'),drop:$('#dropTarget'),empty:$('#emptyState'),viewer:$('#pageViewer'),img:$('#mainImage'),caption:$('#viewerCaption'),panel:$('#editPanel'),count:$('#pageCount'),file:$('#fileInput'),toast:$('#toast'),cropDialog:$('#cropDialog'),cropCanvas:$('#cropCanvas'),cameraDialog:$('#cameraDialog'),video:$('#cameraVideo')};
let pages=[],selectedId=null,stream=null,cropImage=null,corners=defaultCorners(),dragCorner=-1,toastTimer,installPrompt=null;
const selected=()=>pages.find(p=>p.id===selectedId),notify=text=>{ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2600)};
function persist(){return storage.savePages(pages,selectedId).catch(e=>notify(`Could not save locally: ${e.message}`))}
function render(){const page=selected();ui.count.textContent=pages.length;ui.empty.hidden=pages.length>0;ui.viewer.hidden=!page;ui.panel.hidden=!page;$('#deleteBtn').disabled=$('#duplicateBtn').disabled=!page;if(!page){ui.rail.innerHTML='<div class="queue-empty">Pages you capture or import will show up here.</div>';return}ui.img.src=page.src;ui.img.style.filter=cssFilter(page);ui.img.style.transform=`rotate(${page.rotation}deg)`;ui.caption.textContent=`${pages.indexOf(page)+1} / ${pages.length} · ${page.name}`;$('#editPageName').textContent=page.name;$('#brightness').value=page.brightness;$('#contrast').value=page.contrast;$('#brightnessValue').value=`${page.brightness}%`;$('#brightnessValue').textContent=`${page.brightness}%`;$('#contrastValue').value=`${page.contrast}%`;$('#contrastValue').textContent=`${page.contrast}%`;document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===page.filter));const text=$('#ocrText');text.hidden=!page.ocr;text.value=page.ocr;ui.rail.innerHTML='';pages.forEach((p,i)=>{const card=document.createElement('button');card.className=`thumb-card${p.id===selectedId?' selected':''}`;card.draggable=true;card.dataset.id=p.id;card.innerHTML=`<img src="${p.src}" alt="Page ${i+1}" style="filter:${cssFilter(p)};transform:rotate(${p.rotation}deg)"><span class="thumb-number"><span>${i+1}. ${escapeHtml(p.name)}</span><span class="thumb-tag">${p.ocr?'OCR':''}</span></span>`;card.onclick=()=>{selectedId=p.id;render();persist()};card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',p.id);card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();const from=e.dataTransfer.getData('text/plain'),a=pages.findIndex(x=>x.id===from),b=pages.findIndex(x=>x.id===p.id);if(a>=0&&b>=0){pages.splice(b,0,pages.splice(a,1)[0]);render();persist()}});ui.rail.append(card)})}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function imageCanvas(src){const img=new Image();img.src=src;await new Promise((res,rej)=>{img.onload=res;img.onerror=rej});const c=document.createElement('canvas'),scale=Math.min(1,1800/Math.max(img.width,img.height));c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c}
async function addPages(newPages){pages.push(...newPages);if(newPages.length)selectedId=newPages.at(-1).id;render();await persist();if(newPages.length)notify(`${newPages.length} page${newPages.length===1?'':'s'} added`);newPages.forEach(async p=>{try{p.corners=await detectCorners(await imageCanvas(p.src));await persist()}catch{p.corners=null}})}
async function importSelected(files){if(!files.length)return;try{notify('Importing documents…');await addPages(await importFiles([...files]))}catch(e){notify(`Import failed: ${e.message}`)}ui.file.value=''}
$('#importBtn').onclick=$('#bottomImport').onclick=()=>ui.file.click();ui.file.onchange=e=>importSelected(e.target.files);ui.drop.addEventListener('dragover',e=>{e.preventDefault();ui.drop.style.outline='2px solid #328cff'});ui.drop.addEventListener('dragleave',()=>ui.drop.style.outline='');ui.drop.addEventListener('drop',e=>{e.preventDefault();ui.drop.style.outline='';importSelected(e.dataTransfer.files)});
async function openCamera(){try{stream=await startCamera(ui.video);ui.cameraDialog.showModal()}catch(e){notify(e.message);$('#cameraInput').click()}}$('#scanBtn').onclick=$('#bottomScan').onclick=openCamera;$('#cameraInput').onchange=e=>importSelected(e.target.files);$('#closeCamera').onclick=()=>{stopCamera(stream,ui.video);stream=null;ui.cameraDialog.close()};$('#captureBtn').onclick=async()=>{try{await addPages([makePage(captureFrame(ui.video),`Scan ${pages.length+1}`)]);await openCropForSelected(true)}catch(e){notify(e.message)}};$('#switchCameraBtn').onclick=async()=>{try{const facing=ui.video.srcObject?.getVideoTracks()[0]?.getSettings().facingMode==='environment'?'user':'environment';stopCamera(stream,ui.video);stream=await startCamera(ui.video,{facingMode:facing})}catch(e){notify(e.message)}};
$('#deleteBtn').onclick=async()=>{pages=pages.filter(p=>p.id!==selectedId);selectedId=pages.at(-1)?.id||null;render();await persist()};$('#duplicateBtn').onclick=async()=>{const p=selected();if(!p)return;const clone={...p,id:crypto.randomUUID(),name:`${p.name} copy`,createdAt:Date.now()};pages.splice(pages.indexOf(p)+1,0,clone);selectedId=clone.id;render();await persist()};$('#prevPage').onclick=$('#nextPage').onclick=e=>{const dir=e.currentTarget.id==='nextPage'?1:-1,i=pages.findIndex(p=>p.id===selectedId);selectedId=pages[(i+dir+pages.length)%pages.length]?.id;render()};
$('#filterList').onclick=async e=>{const b=e.target.closest('[data-filter]'),p=selected();if(!b||!p)return;p.filter=b.dataset.filter;render();await persist()};$('#brightness').oninput=$('#contrast').oninput=e=>{const p=selected();if(!p)return;p[e.target.id]=Number(e.target.value);render();persist()};$('#rotateBtn').onclick=async()=>{const p=selected();if(p){p.rotation=(p.rotation+90)%360;render();await persist()}};
async function openCropForSelected(auto=false){const p=selected();if(!p)return;cropImage=await imageCanvas(p.src);$('#cropCanvas').width=cropImage.width;$('#cropCanvas').height=cropImage.height;corners=p.corners?.length===4?p.corners.map(x=>[...x]):defaultCorners();drawCrop();ui.cropDialog.showModal();if(auto)await autoCrop()}
$('#cropBtn').onclick=()=>openCropForSelected();$('#closeCrop').onclick=$('#cancelCropBtn').onclick=()=>ui.cropDialog.close();$('#autoCropBtn').onclick=autoCrop;$('#resetCropBtn').onclick=()=>{corners=defaultCorners();drawCrop()};$('#applyCropBtn').onclick=async()=>{const p=selected();if(!p||!cropImage)return;try{p.src=await perspectiveCrop(cropImage,corners)}catch{p.src=boundingCrop(cropImage,corners);notify('OpenCV unavailable; applied a rectangular crop')}p.rotation=0;p.corners=null;render();await persist();ui.cropDialog.close();notify('Crop applied')};
async function autoCrop(){try{const found=await detectCorners(cropImage);corners=found||defaultCorners();drawCrop();notify(found?'Page edges detected':'Using default crop')}catch{corners=defaultCorners();drawCrop();notify('OpenCV unavailable; adjust the default corners')}}
function drawCrop(){const c=ui.cropCanvas,ctx=c.getContext('2d');ctx.drawImage(cropImage,0,0);ctx.beginPath();ctx.rect(0,0,c.width,c.height);corners.forEach(([x,y],i)=>i?ctx.lineTo(x*c.width,y*c.height):ctx.moveTo(x*c.width,y*c.height));ctx.closePath();ctx.fillStyle='#06101b77';ctx.fill('evenodd');ctx.beginPath();corners.forEach(([x,y],i)=>i?ctx.lineTo(x*c.width,y*c.height):ctx.moveTo(x*c.width,y*c.height));ctx.closePath();ctx.lineWidth=Math.max(2,c.width/450);ctx.strokeStyle='#5da9ff';ctx.stroke();corners.forEach(([x,y])=>{ctx.beginPath();ctx.arc(x*c.width,y*c.height,Math.max(10,c.width/48),0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#328cff';ctx.stroke()})}
function pointAt(e){const r=ui.cropCanvas.getBoundingClientRect();return[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]}ui.cropCanvas.onpointerdown=e=>{const [x,y]=pointAt(e);dragCorner=corners.reduce((best,p,i)=>{const d=Math.hypot(p[0]-x,p[1]-y);return d<best.d?{i,d}:best},{i:-1,d:.08}).i;if(dragCorner>=0)ui.cropCanvas.setPointerCapture(e.pointerId)};ui.cropCanvas.onpointermove=e=>{if(dragCorner<0)return;const [x,y]=pointAt(e);corners[dragCorner]=[Math.max(0,Math.min(1,x)),Math.max(0,Math.min(1,y))];drawCrop()};['pointerup','pointercancel','lostpointercapture'].forEach(ev=>ui.cropCanvas.addEventListener(ev,()=>dragCorner=-1));
$('#ocrBtn').onclick=async()=>{const p=selected();if(!p)return;try{notify('Recognizing text…');p.ocr=await recognizeText(p,notify);render();await persist();notify('Text recognition complete')}catch(e){notify(`OCR failed: ${e.message}`)}};$('#ocrText').oninput=e=>{const p=selected();if(p){p.ocr=e.target.value;persist()}};$('#exportJpgBtn').onclick=()=>selected()&&downloadJpgs([selected()]).catch(e=>notify(e.message));$('#exportZipBtn').onclick=()=>pages.length?downloadJpgs(pages).catch(e=>notify(`JPG export failed: ${e.message}`)):notify('Add pages before exporting');
$('#exportBtn').onclick=async()=>{if(!pages.length){notify('Add a page before exporting');return}try{const blob=await downloadPdf(pages);notify('PDF exported');if(navigator.share){const file=new File([blob],'doc-scanner.pdf',{type:'application/pdf'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Scanned document'})}}catch(e){if(e.name!=='AbortError')notify(`Export failed: ${e.message}`)}};$('#shareBtn').onclick=async()=>{if(!pages.length){notify('Add a page to share');return}try{const blob=await buildPdf(pages),file=new File([blob],'doc-scanner.pdf',{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Scanned document'});else notify('Use Export PDF to save a shareable copy')}catch(e){notify(`Share failed: ${e.message}`)}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();installPrompt=null}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
try{pages=await storage.listPages();const meta=JSON.parse(localStorage.getItem('doc-scanner-workspace-v1')||'{}');selectedId=pages.some(p=>p.id===meta.selectedId)?meta.selectedId:pages[0]?.id||null;render()}catch{notify('Local storage is unavailable in this browser')}
